const ResData=[{
    cart:"Soup",
    img:"https://www.indianhealthyrecipes.com/wp-content/uploads/2022/11/tomato-soup-recipe.webp",
    dec:"Tomato Soup",
    price:"119",
    btn:"Add to cart",
},
{
    cart:"Soup",
    img:"https://atozfoodrecipes.com/wp-content/uploads/2015/02/Manchow-Soup.jpg",
    dec:"Manchow Soup",
    price:"110",
    btn:"Add to cart",
},
{
    cart:"Soup",
    img:"https://itsallgoodvegan.com/wp-content/uploads/2020/10/IMG_7091.jpg",
    dec:"Healthy Veg Stew",
    price:"129",
    btn:"Add to cart",
},
{
    cart:"Soup",
    img:"https://thumbs.dreamstime.com/b/cream-mushroom-soup-bowl-delicious-homemade-78954154.jpg",
    dec:"Mushroom Soup",
    price:"140",
    btn:"Add to cart",
},
{
    cart:"Soup",
    img:"https://media.istockphoto.com/id/490027514/photo/corn-soup-in-bowl.jpg?s=612x612&w=0&k=20&c=b5dBQk8CQ3ryGaiAwHWLIYwcq7U4bm6cHGm5xeM_EIw=",
    dec:"Sweet Corn Soup",
    price:"130",
    btn:"Add to cart",
},
{
    cart:"Soup",
    img:"https://articles-1mg.gumlet.io/articles/wp-content/uploads/2020/11/Broccoli-Soup.jpg?compress=true&quality=80&w=640&dpr=2.6",
    dec:"Broccoli Soup",
    price:"180",
    btn:"Add to cart",
},
{
    cart:"MainDish",
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZmTc2o2wVT6eB38fNNIjRJ5nKBcDvok1AFw&s",
    dec:"Mixed Vegetable Curry",
    price:"290",
    btn:"Add to cart",
},
{
    cart:"MainDish",
    img:"https://media-cdn.tripadvisor.com/media/photo-s/12/59/d8/52/indian-main-course-kalyan.jpg",
    dec:"Thali Platter",
    price:"300",
    btn:"Add to cart",
},
{
    cart:"MainDish",
    img:"https://www.foodandwine.com/thmb/KdYtWhepd1x7BNl37PnyOGfXCaA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/peppery-greens-salad-with-avocado-chicken-and-tortilla-croutons-FT-RECIPE0319-0be5ac06443c423e8146241b9498a644.jpg",
    dec:"Avocado Salad",
    price:"280",
    btn:"Add to cart",
},
{
    cart:"MainDish",
    img:"https://ministryofcurry.com/wp-content/uploads/2020/07/panerr-makhani_-scaled.jpg",
    dec:"Paneer Butter Masala",
    price:"220",
    btn:"Add to cart",
},
{
    cart:"MainDish",
    img:"https://3.imimg.com/data3/BV/IW/MY-10144833/chana-masala-punjabi-chhole-masala-500x500.jpg",
    dec:"Punjabi Chole",
    price:"200",
    btn:"Add to cart",
},
{
    cart:"MainDish",
    img:"https://t4.ftcdn.net/jpg/12/55/69/45/360_F_1255694553_gjqazZqr53pXlt1xHNaCMoAFg1vDSabs.jpg",
    dec:"Tandoori Soya Chaap",
    price:"230",
    btn:"Add to cart",
},
{
    cart:"Sweet",
    img:"https://www.lalsweets.com/cdn/shop/articles/b4198e6083.jpg?v=1698824197",
    dec:"Kaju Katli",
    price:"160",
    btn:"Add to cart",
},
{
    cart:"Sweet",
    img:"https://t3.ftcdn.net/jpg/13/03/61/32/360_F_1303613213_gcZ39w8I6nh1V8Ux0qtTKvSf2YxVfGuz.jpg",
    dec:"Rasmalai",
    price:"190",
    btn:"Add to cart",
},
{
    cart:"Sweet",
    img:"https://www.cookwithkushi.com/wp-content/uploads/2021/10/best_gujarati_danedar_mohanthal_recipe-480x270.jpg",
    dec:"Mohanthal",
    price:"190",
    btn:"Add to cart",
},
{
    cart:"Sweet",
    img:"https://blog.swiggy.com/wp-content/uploads/2024/09/Image-1_Gulab-Jamun-1024x538.png",
    dec:"Gulab Jamun",
    price:"230",
    btn:"Add to cart",
},
{
    cart:"Sweet",
    img:"https://static.toiimg.com/thumb/53099699.cms?imgsize=182393&width=800&height=800",
    dec:"Jalebi",
    price:"200",
    btn:"Add to cart",
},
{
    cart:"Sweet",
    img:"https://cdn.dotpe.in/longtail/store-items/1999563/gokzhcpb.jpeg",
    dec:"Anjeer Barfi",
    price:"250",
    btn:"Add to cart",
},
{
    cart:"Beverage",
    img:"https://images.pexels.com/photos/109275/pexels-photo-109275.jpeg?cs=srgb&dl=pexels-fotios-photos-109275.jpg&fm=jpg",
    dec:"Orange Juice",
    price:"290",
    btn:"Add to cart",
},
{
    cart:"Beverage",
    img:"https://info.ehl.edu/hubfs/Blog-EHL-Insights/Blog-Header-EHL-Insights/healthy%20drink.jpeg",
    dec:"Kiwi Juice",
    price:"190",
    btn:"Add to cart",
},
{
    cart:"Beverage",
    img:"https://i.ytimg.com/vi/6X-z0JaaSgM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAJjAdmz_Rm1twYOxFtQ-1sr1nI9A",
    dec:"Strawberry Juice",
    price:"180",
    btn:"Add to cart",
},
{
    cart:"Beverage",
    img:"https://fullofplants.com/wp-content/uploads/2021/05/easy-virgin-mojito-alcohol-free-kid-friendly-refreshing-drink-1.jpg",
    dec:"Mojito",
    price:"110",
    btn:"Add to cart",
},
{
    cart:"Beverage",
    img:"https://media.istockphoto.com/id/1435730496/photo/coconut-juice-and-fresh-young-green-coconut.jpg?s=612x612&w=0&k=20&c=q7mj6zGy_w0QbkwwzfqMh9aVH4Sttcdn3JvOkkq5wWM=",
    dec:"Coconut Water",
    price:"100",
    btn:"Add to cart",
},
{
    cart:"Beverage",
    img:"https://www.orissapost.com/wp-content/uploads/2021/08/Grape-Juice-For-Constipation.jpg",
    dec:"Grapes Juice",
    price:"170",
    btn:"Add to cart",
},
]

export default ResData